name: Terraform CI

on:
    pull_request:
    push:
        branches:
            - develop
    
permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest

        environment:
            name: dev
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.ROLE_ARN }}
                aws-region: "eu-west-1"
            
            - name: Terraform Init
              run: terraform init
            
            - name: Terraform Format Check
              run: terraform fmt -check -diff
            
            - name: Terraform Validate
              run: terraform validate
            
            - name: Terraform Plan
              run: terraform plan -out=tfplan
            
            - name: Upload Plan Artifact
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: tfplan