name: Terraform CD

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: prod

        concurrency:
            group: terraform-prod
            cancel-in-progress: false
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Download Plan Artifact
              run: aws s3 cp s3://terraform-plan-hitesh/tfplan tfplan
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.ROLE_ARN }}
                aws-region: "eu-west-1"
            
            - name: Terraform Init
              run: terraform init
            
            - name: Apply Terraform
              run: terraform apply -auto-approve tfplan